// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapigen

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuditLogEventResult.
const (
	Failure AuditLogEventResult = "failure"
	Success AuditLogEventResult = "success"
)

// Valid indicates whether the value is a known member of the AuditLogEventResult enum.
func (e AuditLogEventResult) Valid() bool {
	switch e {
	case Failure:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	Active    UserStatus = "active"
	Inactive  UserStatus = "inactive"
	Suspended UserStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Inactive:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// AssignRoleRequest defines model for AssignRoleRequest.
type AssignRoleRequest struct {
	RoleId string `json:"role_id"`
}

// AuditLogEvent defines model for AuditLogEvent.
type AuditLogEvent struct {
	Action      string                  `json:"action"`
	ActorUserId *string                 `json:"actor_user_id,omitempty"`
	CreatedAt   time.Time               `json:"created_at"`
	Id          string                  `json:"id"`
	Metadata    *map[string]interface{} `json:"metadata,omitempty"`
	RequestId   *string                 `json:"request_id,omitempty"`
	Resource    string                  `json:"resource"`
	ResourceId  *string                 `json:"resource_id,omitempty"`
	Result      AuditLogEventResult     `json:"result"`
}

// AuditLogEventResult defines model for AuditLogEvent.Result.
type AuditLogEventResult string

// AuditLogListResponse defines model for AuditLogListResponse.
type AuditLogListResponse struct {
	Data  []AuditLogEvent `json:"data"`
	Limit int             `json:"limit"`
	Total int             `json:"total"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}

// CreateRoleRequest defines model for CreateRoleRequest.
type CreateRoleRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email    openapi_types.Email `json:"email"`
	FullName *string             `json:"full_name,omitempty"`
	Password string              `json:"password"`
	Username *string             `json:"username,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Example: internal_error
		Code string `json:"code"`

		// Message Example: something went wrong
		Message string `json:"message"`
	} `json:"error"`
}

// GrantPermissionRequest defines model for GrantPermissionRequest.
type GrantPermissionRequest struct {
	// Code Example: users:read
	Code string `json:"code"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Role defines model for Role.
type Role struct {
	Description *string `json:"description,omitempty"`
	Id          string  `json:"id"`
	IsSystem    bool    `json:"is_system"`
	Name        string  `json:"name"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	FullName *string    `json:"full_name,omitempty"`
	Status   UserStatus `json:"status"`
	Username *string    `json:"username,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	FullName  *string             `json:"full_name,omitempty"`
	Id        string              `json:"id"`
	Status    UserStatus          `json:"status"`
	UpdatedAt time.Time           `json:"updated_at"`
	Username  *string             `json:"username,omitempty"`
}

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Data  []User `json:"data"`
	Limit int    `json:"limit"`
	Total int    `json:"total"`
}

// UserStatus defines model for UserStatus.
type UserStatus string

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Error struct {
		// Code Example: validation_error
		Code   string `json:"code"`
		Fields []struct {
			Field   string `json:"field"`
			Message string `json:"message"`
		} `json:"fields"`
	} `json:"error"`
}

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	Action      *string `form:"action,omitempty" json:"action,omitempty"`
	ActorUserId *string `form:"actor_user_id,omitempty" json:"actor_user_id,omitempty"`
	Limit       *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset      *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Status *UserStatus `form:"status,omitempty" json:"status,omitempty"`
	Search *string     `form:"search,omitempty" json:"search,omitempty"`
	Limit  *int        `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int        `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = CreateRoleRequest

// GrantPermissionToRoleJSONRequestBody defines body for GrantPermissionToRole for application/json ContentType.
type GrantPermissionToRoleJSONRequestBody = GrantPermissionRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// AssignRoleToUserJSONRequestBody defines body for AssignRoleToUser for application/json ContentType.
type AssignRoleToUserJSONRequestBody = AssignRoleRequest
